### ISSUE TITLE
Runtime error on Ubuntu 16.04

### ISSUE THREAD

**Issue by kasteph** [bakwc/OpenSpell#17]
I am using the Python bindings for Jamspell. Assuming that I have the following Dockerfile:

```
FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt install -y build-essential libstdc++6 wget git swig libssl-dev python3.6 python3.6-dev python3-pip python3.6-venv

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN python3.6 -m pip install pip --upgrade
RUN python3.6 -m pip install wheel

COPY . /app

WORKDIR /app

RUN python3.6 -m pip install -r requirements.txt

CMD ["python3.6", "-m", "http.server"]
```

I get the following error on `import jamspell`:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```

The locales are set with the `ENV` directives and when checking the locales with `locale` on interactive terminal in Docker, `LANG` and `LC_ALL` are set. Is there anything that I'm missing with my dependencies?

Cheers,
steph

**Comment by bakwc** [comment]
Thanks for report! Currently I'm setting locale "en_US.UTF-8" and ignore system locale. Apparently this is wrong, I'll try to fix, meanwhile you can try to install "en_US.UTF-8" locale to your system.

**Comment by stephsamson** [comment]
Thanks @bakwc! For anyone else running into this issue:

```
apt-get install locales
locale-gen en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

... worked for me.

**Comment by Raphencoder** [comment]
Hi, Thanks for Jamspell it's a very very good library!

I have the same problem running on Unbutu 16.04
Here is my Dockerfile (pretty simple)

```Dockerfile
FROM python:3.5.2

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN pip install --upgrade pip && pip install --upgrade setuptools

RUN pip install jamspell
```
I run this command: 
```
sudo docker build -t enmisspells .

```
And I have the following error 

```
Step 6/6 : RUN pip install jamspell
 ---> Running in cca7593ee462
Collecting jamspell
  Downloading https://files.pythonhosted.org/packages/5a/16/0a808e926a835604007066085cb2183b337694a06240a99945b31fa14f27/jamspell-0.0.11.tar.gz (60kB)
Installing collected packages: jamspell
  Running setup.py install for jamspell: started
    Running setup.py install for jamspell: finished with status 'error'
    Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lil8v5f0/jamspell/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hqzp9o5l/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building '_jamspell' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lil8v5f0/jamspell/setup.py", line 73, in <module>
        include_package_data=True,
      File "/usr/local/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-lil8v5f0/jamspell/setup.py", line 39, in run
        self.run_command('build_ext')
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 504, in build_extension
        sources = self.swig_sources(sources, ext)
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 595, in swig_sources
        swig = self.swig or self.find_swig()
      File "/tmp/pip-install-lil8v5f0/jamspell/setup.py", line 45, in find_swig
        assert swigBinary is not None
    AssertionError
    
    ----------------------------------------
Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lil8v5f0/jamspell/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hqzp9o5l/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-lil8v5f0/jamspell/
```
I also tried adding this to my Dockerfile
```
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
```
But I don't have the locale.gen in my container:

```
sed: can't read /etc/locale.gen: No such file or directory
The command '/bin/sh -c sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &&     dpkg-reconfigure --frontend=noninteractive locales &&     update-locale LANG=en_US.UTF-8' returned a non-zero code: 2

```
Is there any solutions or correction to do ?
Thanks ! :+1:

**Comment by ShaileshSridhar2403** [comment]
Needed to add

`
echo "LC_ALL=en_US.UTF-8" >> /etc/environment && \
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
echo "LANG=en_US.UTF-8" > /etc/locale.conf && \
locale-gen en_US.UTF-8
`

To get it to work

**Comment by sibiryoff** [comment]
All workarounds did not work for me. Debian 10.

**Comment by romikforest** [comment]
I used for python:3.9.5-buster docker container (Debian based, not ubuntu):

RUN set -e ; \
  apt-get update -y ; \
  DEBIAN_FRONTEND=noninteractive apt-get install -y locales ;\
  echo "en_US.UTF-8 UTF-8" > /etc/locale.gen ; \
  locale-gen ; \
  DEBIAN_FRONTEND=noninteractive apt-get install -y swig3.0 ; \
  apt-get clean ; \
  rm -rf /var/lib/apt/lists/*

**Comment by ziggycross** [comment]
Using `python:3.11-buster` with @romikforest's solution worked for me. I could not it to work with standard `python:3.11`.
